<a href="https://colab.research.google.com/github/veenussudarsan/pythonbasics/blob/main/Copy_of_Untitled14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
supermarket=files.upload()

Saving Supermarket_sales.csv to Supermarket_sales.csv


In [ ]:
import pandas as pd
dataframe=pd.read_csv("Supermarket_sales.csv")
print(dataframe)

       No    InvoiceID Branch       City Customertype  Gender  \
0       1  750-67-8428      A     Yangon       Member  Female   
1       2  226-31-3081      C  Naypyitaw       Normal  Female   
2       3  631-41-3108      A     Yangon       Normal    Male   
3       4  123-19-1176      A     Yangon       Member    Male   
4       5  373-73-7910      A     Yangon       Normal    Male   
..    ...          ...    ...        ...          ...     ...   
995   996  233-67-5758      C  Naypyitaw       Normal    Male   
996   997  303-96-2227      B   Mandalay       Normal  Female   
997   998  727-02-1313      A     Yangon       Member    Male   
998   999  347-56-2442      A     Yangon       Normal    Male   
999  1000  849-09-3807      A     Yangon       Member  Female   

                Productline  Unitprice  Quantity      Tax      Total  \
0         Health and beauty      74.69         7  26.1415   548.9715   
1    Electronic accessories      15.28         5   3.8200    80.2200   
2  

In [ ]:
dataframe.head()

No    InvoiceID Branch       City Customertype  Gender  \
0   1  750-67-8428      A     Yangon       Member  Female   
1   2  226-31-3081      C  Naypyitaw       Normal  Female   
2   3  631-41-3108      A     Yangon       Normal    Male   
3   4  123-19-1176      A     Yangon       Member    Male   
4   5  373-73-7910      A     Yangon       Normal    Male   

              Productline  Unitprice  Quantity      Tax     Total       Date  \
0       Health and beauty      74.69         7  26.1415  548.9715   1/5/2019   
1  Electronic accessories      15.28         5   3.8200   80.2200   3/8/2019   
2      Home and lifestyle      46.33         7  16.2155  340.5255   3/3/2019   
3       Health and beauty      58.22         8  23.2880  489.0480  1/27/2019   
4       Sports and travel      86.31         7  30.2085  634.3785   2/8/2019   

    Time      Payment    cogs  gross_margin_percentage  gross_iincome  Rating  
0  13:08      Ewallet  522.83                 4.761905        26.1415     9.1  
1  10:29         Cash   76.40                 4.761905         3.8200     9.6  
2  13:23  Credit card  324.31                 4.761905        16.2155     7.4  
3  20:33      Ewallet  465.76                 4.761905        23.2880     8.4  
4  10:37      Ewallet  604.17                 4.761905        30.2085     5.3

In [ ]:
dataframe.tail(8)

No    InvoiceID Branch       City Customertype  Gender  \
992   993  745-74-0715      A     Yangon       Normal    Male   
993   994  690-01-6631      B   Mandalay       Normal    Male   
994   995  652-49-6720      C  Naypyitaw       Member  Female   
995   996  233-67-5758      C  Naypyitaw       Normal    Male   
996   997  303-96-2227      B   Mandalay       Normal  Female   
997   998  727-02-1313      A     Yangon       Member    Male   
998   999  347-56-2442      A     Yangon       Normal    Male   
999  1000  849-09-3807      A     Yangon       Member  Female   

                Productline  Unitprice  Quantity      Tax      Total  \
992  Electronic accessories      58.03         2   5.8030   121.8630   
993     Fashion accessories      17.49        10   8.7450   183.6450   
994  Electronic accessories      60.95         1   3.0475    63.9975   
995       Health and beauty      40.35         1   2.0175    42.3675   
996      Home and lifestyle      97.38        10  48.6900  1022.4900   
997      Food and beverages      31.84         1   1.5920    33.4320   
998      Home and lifestyle      65.82         1   3.2910    69.1110   
999     Fashion accessories      88.34         7  30.9190   649.2990   

          Date   Time  Payment    cogs  gross_margin_percentage  \
992  3/10/2019  20:46  Ewallet  116.06                 4.761905   
993  2/22/2019  18:35  Ewallet  174.90                 4.761905   
994  2/18/2019  11:40  Ewallet   60.95                 4.761905   
995  1/29/2019  13:46  Ewallet   40.35                 4.761905   
996   3/2/2019  17:16  Ewallet  973.80                 4.761905   
997   2/9/2019  13:22     Cash   31.84                 4.761905   
998  2/22/2019  15:33     Cash   65.82                 4.761905   
999  2/18/2019  13:28     Cash  618.38                 4.761905   

     gross_iincome  Rating  
992         5.8030     8.8  
993         8.7450     6.6  
994         3.0475     5.9  
995         2.0175     6.2  
996        48.6900     4.4  
997         1.5920     7.7  
998         3.2910     4.1  
999        30.9190     6.6

In [ ]:
dataframe.loc[4]

No                                         5
InvoiceID                        373-73-7910
Branch                                     A
City                                  Yangon
Customertype                          Normal
Gender                                  Male
Productline                Sports and travel
Unitprice                              86.31
Quantity                                   7
Tax                                  30.2085
Total                               634.3785
Date                                2/8/2019
Time                                   10:37
Payment                              Ewallet
cogs                                  604.17
gross_margin_percentage             4.761905
gross_iincome                        30.2085
Rating                                   5.3
Name: 4, dtype: object

In [ ]:
dataframe[['City']]

City
0       Yangon
1    Naypyitaw
2       Yangon
3       Yangon
4       Yangon
..         ...
995  Naypyitaw
996   Mandalay
997     Yangon
998     Yangon
999     Yangon

[1000 rows x 1 columns]

In [ ]:
dataframe=dataframe.drop(['Tax'],axis=1)
dataframe.head(4)

No    InvoiceID Branch       City Customertype  Gender  \
0   1  750-67-8428      A     Yangon       Member  Female   
1   2  226-31-3081      C  Naypyitaw       Normal  Female   
2   3  631-41-3108      A     Yangon       Normal    Male   
3   4  123-19-1176      A     Yangon       Member    Male   

              Productline  Unitprice  Quantity     Total       Date   Time  \
0       Health and beauty      74.69         7  548.9715   1/5/2019  13:08   
1  Electronic accessories      15.28         5   80.2200   3/8/2019  10:29   
2      Home and lifestyle      46.33         7  340.5255   3/3/2019  13:23   
3       Health and beauty      58.22         8  489.0480  1/27/2019  20:33   

       Payment    cogs  gross_margin_percentage  gross_iincome  Rating  
0      Ewallet  522.83                 4.761905        26.1415     9.1  
1         Cash   76.40                 4.761905         3.8200     9.6  
2  Credit card  324.31                 4.761905        16.2155     7.4  
3      Ewallet  465.76                 4.761905        23.2880     8.4

In [ ]:
from google.colab import files
players=files.upload()

Saving players_20.csv to players_20.csv


In [ ]:
fifadataframe = pd.read_csv("players_20.csv")
max_overall=fifadataframe.age.idxmax()
#max_overall_loc= fifadataframe.overall.idxmax()
#person = fifadataframe.loc[max_overall_loc]


In [ ]:
fifadataframe.loc[fifadataframe['club']=="FC Barcelona"]

sofifa_id                                         player_url  \
0         158023  https://sofifa.com/player/158023/lionel-messi/...   
6         192448  https://sofifa.com/player/192448/marc-andre-te...   
19        176580  https://sofifa.com/player/176580/luis-suarez/2...   
21        189511  https://sofifa.com/player/189511/sergio-busque...   
22        194765  https://sofifa.com/player/194765/antoine-griez...   
29        152729  https://sofifa.com/player/152729/gerard-pique-...   
51        189332  https://sofifa.com/player/189332/jordi-alba-ra...   
59        205600  https://sofifa.com/player/205600/samuel-umtiti...   
64        168651  https://sofifa.com/player/168651/ivan-rakitic/...   
75        228702  https://sofifa.com/player/228702/frenkie-de-jo...   
84        220440  https://sofifa.com/player/220440/clement-lengl...   
91        194404  https://sofifa.com/player/194404/norberto-mura...   
110       231443  https://sofifa.com/player/231443/ousmane-dembe...   
115       230658  https://sofifa.com/player/230658/arthur-henriq...   
142       181872  https://sofifa.com/player/181872/arturo-vidal/...   
249       227928  https://sofifa.com/player/227928/nelson-cabral...   
274       199564  https://sofifa.com/player/199564/sergio-robert...   
344       201400  https://sofifa.com/player/201400/rafael-alcant...   
602       241184  https://sofifa.com/player/241184/hector-junior...   
1276      233113  https://sofifa.com/player/233113/carles-alena-...   
4042      242816  https://sofifa.com/player/242816/ricard-puig-m...   
4045      245388  https://sofifa.com/player/245388/jean-clair-to...   
4068      237156  https://sofifa.com/player/237156/moussa-wague/...   
4780      237823  https://sofifa.com/player/237823/hiroki-abe/20...   
4781      240683  https://sofifa.com/player/240683/ludovit-reis/...   
6634      239250  https://sofifa.com/player/239250/abel-ruiz-ort...   
7711      239249  https://sofifa.com/player/239249/oriol-busquet...   
7712      240654  https://sofifa.com/player/240654/carles-perez-...   
7713      240915  https://sofifa.com/player/240915/juan-miranda-...   
9908      241810  https://sofifa.com/player/241810/juan-brandari...   
9938      242999  https://sofifa.com/player/242999/alex-collado-...   
9970      237522  https://sofifa.com/player/237522/jorge-cuenca-...   
11042     246139  https://sofifa.com/player/246139/ignacio-pena-...   

            short_name                            long_name  age         dob  \
0             L. Messi       Lionel Andrés Messi Cuccittini   32  1987-06-24   
6        M. ter Stegen                Marc-André ter Stegen   27  1992-04-30   
19           L. Suárez             Luis Alberto Suárez Díaz   32  1987-01-24   
21     Sergio Busquets             Sergio Busquets i Burgos   30  1988-07-16   
22        A. Griezmann                    Antoine Griezmann   28  1991-03-21   
29               Piqué                Gerard Piqué Bernabéu   32  1987-02-02   
51          Jordi Alba                     Jordi Alba Ramos   30  1989-03-21   
59           S. Umtiti                        Samuel Umtiti   25  1993-11-14   
64          I. Rakitić                         Ivan Rakitić   31  1988-03-10   
75          F. de Jong                      Frenkie de Jong   22  1997-05-12   
84          C. Lenglet                      Clément Lenglet   24  1995-06-17   
91                Neto                 Norberto Murara Neto   29  1989-07-19   
110         O. Dembélé                      Ousmane Dembélé   22  1997-05-15   
115             Arthur  Arthur Henrique Ramos Oliveira Melo   22  1996-08-12   
142           A. Vidal                         Arturo Vidal   32  1987-05-22   
249      Nélson Semedo                 Nélson Cabral Semedo   25  1993-11-16   
274      Sergi Roberto              Sergio Roberto Carnicer   27  1992-02-07   
344            Rafinha       Rafael Alcântara do Nascimento   26  1993-02-12   
602       Junior Firpo           Héctor Junior Firpo Adamés   22  1996-0

In [ ]:
import numpy as np

In [ ]:
students_marks_BA=[12,14,15]
marksarray=np.array(students_marks_BA)
print(marksarray)

[12 14 15]


In [ ]:
student_marks=[[12,14,10],[15,19,30],[11,15,19]]
marksarray=np.array(student_marks)
print(marksarray)

[[12 14 10]
 [15 19 30]
 [11 15 19]]


In [ ]:
values=np.arange(1,11)
print(values)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
values2=np.arange(5,11)
print(values2)

[ 5  6  7  8  9 10]


In [ ]:
values3=np.arange(1,11,2)
print(values3)

[1 3 5 7 9]


In [ ]:
zeroarray = np.zeros(5)
print(zeroarray)

[0. 0. 0. 0. 0.]


In [ ]:
zeroarray=np.zeros((2,6))
print(zeroarray)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
zeroarray=np.zeros((4,2))
print(zeroarray)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
identityarray=np.eye(10,10)
print(identityarray)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
